### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'count'

### ISSUE THREAD

**Issue by brentneave** [yargies/lektor-datapages#1]
Hi there. 

I’m having an issue getting lektor-datapages to compile. Starting with a brand new Lektor project. 

Add this to the end of `models/page.ini`:
```
[fields.pages]
label = Data Pages
type = datapages
size = large
```

`/content/contents.lr` looks like this:
```
title: Welcome to pmg-lektor!
---
body:

This is a basic demo website that shows how to use Lektor for a basic
website with some pages.
---
pages: exhibitions.all, ID, page.html
```

`databags/exhibitions.json` looks like this:
```
{
    "all": [
    {
        "ID": 854,
        "Title": "...",
        "StartDate": "2017-11-15",
        "EndDate": "2017-12-09",
        "Description": "...",
        "Artists": ["43"],
        "Artworks": ["850", "852", "851", "849", "853", "855"]
    },
    …]
}
```

Lektor runs into a problem here (copied from Terminal output):
```
Started source info update
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Finished source info update in 0.01 sec
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 44, in build
    builder.update_all_source_infos()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1129, in update_all_source_infos
    self.extend_build_queue(to_build, prog)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1090, in extend_build_queue
    queue.extend(prog.iter_child_sources())
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 1002, in __iter__
    for item in iterable:
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 873, in _iterate
    record = self._get(name, persist=False)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 837, in _get
    alt=self.alt, page_num=page_num)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 1552, in get
    rv = self.instance_from_data(raw_data, page_num=page_num)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/db.py", line 1595, in instance_from_data
    data = datamodel.process_raw_data(raw_data, self)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/datamodel.py", line 368, in process_raw_data
    rv[field.name] = field.deserialize_value(value, pad=pad)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/datamodel.py", line 200, in deserialize_value
    return self.type.value_from_raw_with_default(raw_value)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/types/__init__.py", line 83, in value_from_raw_with_default
    value = self.value_from_raw(raw)
  File "/Users/brentneave/Library/Caches/Lektor/packages/ee8b82d1ff1b4a92fbc2ce6b5284ae1c/lektor_data_pages.py", line 98, in value_from_raw
    assert raw.value.count(',') == 2
AttributeError: 'NoneType' object has no attribute 'count'
```

**Comment by rponline** [comment]
I've exactly the same issue.
